-----
# 요약  
## 기본 연산  
* 벡터, 행렬, 텐서  
### Slicing  
* 기본 형태  
* 음수  
* 빈 경우  

### Dimension 함수  
* dim(), size(), shape  
* ndim, shape  

### 행렬 간 연산  
#### 덧셈  
* 브로드캐스팅  

#### 곱셈  
* 행렬곱  
* 곱  

### 통계 함수  
* mean, sum, max, argmax  
* dim  
* 연산 후 차원
- ## 연산
    - ### View
        - -1
        - [input_sequence]
    - ### Squeeze
        - 용도
        - Dim
    - ### Unsqeeze
    - ### Type Casting
        - 형식
    - ### Concatenate
        - 형식
        - dim
        - 출력행렬 크기
    - ### stack
        - 형식
        - dim
        - 출력행렬 크기
    - ### Ones and Zeros
        - 형식
        - _like
        - full
    - ### In-place Operation
        - _

------

# 내용
## 기본 연산

### Slicing
- 기본 형태  
- 음수  
- 빈 경우  

In [1]:
import numpy as np
import torch

In [2]:
## numpy 예시
t = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
print(t)
# [ 0.  1.  2.  3.  4.  5.  6.]

print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)
# Rank of t:  1
# Shape of t:  (7,)

print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])  # Element
print("t[2:5] t[4:-1]  = ", t[2:5], t[4:-1])  # Slicing
print("t[:2] t[3:]     = ", t[:2], t[3:])  # Slicing

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [3]:
## pytorch 예시
## 곱셈,행렬곱 체크
t = torch.FloatTensor([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
print(t)
# tensor([0., 1., 2., 3., 4., 5., 6.])

print(t.dim())  # rank
# 1

print(t.shape)  # shape
# torch.Size([7])

print(t.size())  # shape
# torch.Size([7])

print(t[0], t[1], t[-1])  # Element
# tensor(0.) tensor(1.) tensor(6.)

print(t[2:5], t[4:-1])  # Slicing
# tensor([2., 3., 4.]) tensor([4., 5.])

print(t[:2], t[3:])  # Slicing
# tensor([0., 1.]) tensor([3., 4., 5., 6.])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### Dimension 함수
- dim(), size(), shape  
- ndim, shape  


In [4]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

# 출력 결과는 다음과 같을 것입니다:
# tensor([[ 1.,  2.,  3.],
#         [ 4.,  5.,  6.],
#         [ 7.,  8.,  9.],
#         [10., 11., 12.]])

print(t.dim())  # rank - 차원 수
print(t.size())  # shape - 텐서의 형태

# 이미지에서 보이는 것으로 t[1] 출력하는 부분이 있는데, 이는 두 번째 행을 의미합니다.
print(t[1])

print(t[:, 1].size())  # 모든 행의 두 번째 열의 크기
print(t[:, :-1])  # 모든 행과 마지막 열을 제외한 모든 열

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([4., 5., 6.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])



### 행렬 간 연산
#### 덧셈
- 브로드캐스팅  


In [5]:
## 브로드캐스팅 예제
## 커지는 모양 체크

# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)
# tensor([[5., 5.]])

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])  # 3 -> [[3, 3]]
print(m1 + m2)
# tensor([[4., 5.]])

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])  # 1x2 벡터
m2 = torch.FloatTensor([[3], [4]])  # 2x1 벡터
print(m1 + m2)
# tensor([[4., 5.],
#         [5., 6.]])

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])



#### 곱셈
- 행렬곱  
- 곱  


In [6]:
## 곱, 행렬곱
print()
print("---------------")
print("Mat vs Matmul")
print("---------------")

# 첫 번째 예제: matmul 연산
m1 = torch.FloatTensor([[1, 2], [3, 4]])  # 2×2 행렬
m2 = torch.FloatTensor([[3], [2]])  # 2×1 행렬(열 벡터)
print("Shape of Matrix 1: ", m1.shape)  # 2 x 2
print("Shape of Matrix 2: ", m2.shape)  # 2 x 1
print(m1.matmul(m2))  # 행렬 곱셈 결과 (2×1 행렬)

# 두 번째 예제: 원소별 곱셈(element-wise multiplication)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[3], [2]])
print("Shape of Matrix 1: ", m1.shape)  # 2 x 2
print("Shape of Matrix 2: ", m2.shape)  # 2 x 1
print(m1 * m2)  # 브로드캐스팅된 원소별 곱셈
print(m1.mul(m2))  # mul() 메소드도 동일한 결과


---------------
Mat vs Matmul
---------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 7.],
        [17.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[3., 6.],
        [6., 8.]])
tensor([[3., 6.],
        [6., 8.]])


### 통계 함수
- mean, sum, max, argmax  
- dim  
- 연산 후 차원

In [ ]:
## mean, sum, max, argmax
## 행렬 크기 직관적으로 볼 떄는 바깥쪽부터 원소수를 세면서 대괄호를 하나씩 제거해나가면 됨
## n 차원 행렬에 대해 차원 지정해 연산시 지정한 차원이 사라진 n-1 차원의 행렬을 출력으로 내보낸다
## keepdim=True 로 설정 시 지정된 차원이 사리지지 않고 크기가 1로 변한다.
## 여러 차원을 선택히 모든 지정차원이 사라진다
## dim 에 해당되지 않으면 다른 인덱스는 고정시키고, dim 에 해당되는 인덱스만 값을 변경시키며 연산한다.


# 1. 기본적인 평균 계산 - 1차원 텐서
t = torch.FloatTensor([1, 2])
print(t.mean())  # tensor(1.5000)

# 2. 정수형 텐서(LongTensor)에서는 mean() 사용 불가
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)  # Can only calculate the mean of floating types. Got Long instead.

# 3. 고차원 텐서 생성
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
# tensor([[1., 2.],
#         [3., 4.]])

# 4. 다양한 차원에서의 평균 계산
print(t.mean())  # 모든 원소의 평균: tensor(2.5000)
print(t.mean(dim=0))  # 열 방향 평균(각 열에 대한 평균): tensor([2., 3.])
print(t.mean(dim=1))  # 행 방향 평균(각 행에 대한 평균): tensor([1.5000, 3.5000])
print(t.mean(dim=-1))  # 마지막 차원 방향 평균(dim=1과 동일): tensor([1.5000, 3.5000])

tensor(1.5000)
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [8]:
## argmax
## 요소 중 최대값을 가진 인덱스 반환

# 3차원 텐서 생성  
t = torch.FloatTensor([[1, 2], [3, 4]])  
print(t)  
print("텐서 shape:", t.shape)  # [ 2, 2]  

# 차원 지정 없이 max 호출 - 모든 요소 중 최댓값 반환  
print(t.max())  # Returns one value: max  

# dim=0 지정하여 max 호출 - 첫 번째 차원을 따라 최댓값과 인덱스 반환  
print(t.max(dim=0))  # Returns two values: max and argmax  
print("Max: ", t.max(dim=0)[0])  
print("Argmax: ", t.max(dim=0)[1])  

# dim=1 지정하여 max 호출 - 두 번째 차원을 따라 최댓값 계산  
print(t.max(dim=1))  

# dim=-1 지정하여 max 호출 - 마지막 차원을 따라 최댓값 계산  
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
텐서 shape: torch.Size([2, 2])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### Reshape
- View
    - -1
        - 알아서 자동으로 크기를 계산하는 차원을 말함
        - 입력된 다른 차원 모양을 계산하고 남는 크기를 알아서 맞추는 방법이므로 차원 하나만 -1이 될수있음
    - [input_sequence]
        - 행렬의 모든 데이터를 일렬로 펼친 후, 입력된 모양에 맞게 재배치함
        - 총 원소의 수는 반드시 같아야함
        

In [9]:
# 3차원 NumPy 배열 생성 (2x2x3 형태)  
t = np.array([[[0, 1, 2],  
               [3, 4, 5]],  
              
              [[6, 7, 8],  
               [9, 10, 11]]])  

# NumPy 배열을 PyTorch 텐서로 변환  
ft = torch.FloatTensor(t)  

# 텐서의 형태(shape) 출력  
print(ft.shape)  # 결과: torch.Size([2, 2, 3])

torch.Size([2, 2, 3])


In [10]:
# ft.view([-1, 3])은 텐서를 재구성합니다:  
# - 마지막 차원은 3  
# - 첫 번째 차원(-1)은 자동으로 계산됨  
print(ft.view([-1, 3]))  
print(ft.view([-1, 3]).shape)  # 결과: torch.Size([4, 3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [11]:
# 마지막으로, 3차원 텐서로 재구성:  
# - 마지막 차원은 3  
# - 중간 차원은 1  
# - 첫 번째 차원(-1)은 자동으로 계산됨  
print(ft.view([-1, 1, 3]))  
print(ft.view([-1, 1, 3]).shape)  # 결과: torch.Size([4, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- 크기가 1인 단일 차원 제거
- dim
    - 지정된 차원의 크기가 1인 경우 제거
    - 값이랑 무관
    

In [12]:
import torch  

# squeeze()의 dim 파라미터 다양한 사용 예제  
def demonstrate_squeeze_with_dim():  
    # 테스트용 다차원 텐서 생성 (형태: [1,2,1,3,1])  
    tensor = torch.randn(1, 2, 1, 3, 1)  
    print(f"원본 텐서 형태: {tensor.shape}")  
    
    # 1. dim 지정 없이 모든 단일 차원 제거  
    print(f"\n모든 단일 차원 제거 - squeeze(): {tensor.squeeze().shape}")  # [2,3]  
    
    # 2. 양수 인덱스로 특정 차원 squeeze  
    print(f"\n특정 차원만 squeeze:")  
    print(f"squeeze(dim=0): {tensor.squeeze(dim=0).shape}")    # [2,1,3,1] - 첫 번째 차원(인덱스 0) 제거  
    print(f"squeeze(dim=2): {tensor.squeeze(dim=2).shape}")    # [1,2,3,1] - 세 번째 차원(인덱스 2) 제거  
    print(f"squeeze(dim=4): {tensor.squeeze(dim=4).shape}")    # [1,2,1,3] - 다섯 번째 차원(인덱스 4) 제거  
    
    # 3. 크기가 1이 아닌 차원에 squeeze 시도 (변화 없음)  
    print(f"\n크기가 1이 아닌 차원 squeeze 시도:")  
    print(f"squeeze(dim=1): {tensor.squeeze(dim=1).shape}")    # [1,2,1,3,1] - 변화 없음 (크기가 1이 아님)  
    print(f"squeeze(dim=3): {tensor.squeeze(dim=3).shape}")    # [1,2,1,3,1] - 변화 없음 (크기가 1이 아님)  
    
    # 4. 음수 인덱스로 차원 지정 (-1: 마지막 차원)  
    print(f"\n음수 인덱스 사용:")  
    print(f"squeeze(dim=-1): {tensor.squeeze(dim=-1).shape}")  # [1,2,1,3] - 마지막 차원 제거  
    print(f"squeeze(dim=-3): {tensor.squeeze(dim=-3).shape}")  # [1,2,3,1] - 뒤에서 세 번째 차원 제거  
    print(f"squeeze(dim=-5): {tensor.squeeze(dim=-5).shape}")  # [2,1,3,1] - 뒤에서 다섯 번째(첫 번째) 차원 제거  
    
    # 5. 여러 번 squeeze 연속 적용  
    print(f"\n여러 차원 순차적으로 squeeze:")  
    result = tensor.squeeze(dim=0).squeeze(dim=1).squeeze(dim=-1)  
    print(f"순차 squeeze 결과: {result.shape}")  # [2,3]  
    
    # 6. dim 파라미터의 다양한 문법  
    print(f"\n다양한 dim 파라미터 문법:")  
    print(f"squeeze(0): {tensor.squeeze(0).shape}")          # 위치 인자  
    print(f"squeeze(dim=0): {tensor.squeeze(dim=0).shape}")  # 키워드 인자  

# 함수 실행  
demonstrate_squeeze_with_dim()

원본 텐서 형태: torch.Size([1, 2, 1, 3, 1])

모든 단일 차원 제거 - squeeze(): torch.Size([2, 3])

특정 차원만 squeeze:
squeeze(dim=0): torch.Size([2, 1, 3, 1])
squeeze(dim=2): torch.Size([1, 2, 3, 1])
squeeze(dim=4): torch.Size([1, 2, 1, 3])

크기가 1이 아닌 차원 squeeze 시도:
squeeze(dim=1): torch.Size([1, 2, 1, 3, 1])
squeeze(dim=3): torch.Size([1, 2, 1, 3, 1])

음수 인덱스 사용:
squeeze(dim=-1): torch.Size([1, 2, 1, 3])
squeeze(dim=-3): torch.Size([1, 2, 3, 1])
squeeze(dim=-5): torch.Size([2, 1, 3, 1])

여러 차원 순차적으로 squeeze:
순차 squeeze 결과: torch.Size([2, 3])

다양한 dim 파라미터 문법:
squeeze(0): torch.Size([2, 1, 3, 1])
squeeze(dim=0): torch.Size([2, 1, 3, 1])


### Unsqueeze
    - 지정된 dim 차원에 크기가 1인 새 차원을 삽입함

In [13]:
import torch  

# unsqueeze()의 다양한 사용 예제  
def demonstrate_unsqueeze_with_dim():  
    # 테스트용 텐서 생성 (형태: [2,3])  
    tensor = torch.randn(2, 3)  
    print(f"원본 텐서 형태: {tensor.shape}")  
    
    # 1. 다양한 위치에 차원 추가  
    print(f"\n다양한 위치에 차원 추가:")  
    print(f"unsqueeze(dim=0): {tensor.unsqueeze(dim=0).shape}")  # [1,2,3] - 첫 번째 위치에 차원 추가  
    print(f"unsqueeze(dim=1): {tensor.unsqueeze(dim=1).shape}")  # [2,1,3] - 두 번째 위치에 차원 추가  
    print(f"unsqueeze(dim=2): {tensor.unsqueeze(dim=2).shape}")  # [2,3,1] - 세 번째 위치에 차원 추가  
    
    # 2. 음수 인덱스로 차원 지정 (-1: 마지막 위치 이후)  
    print(f"\n음수 인덱스 사용:")  
    print(f"unsqueeze(dim=-1): {tensor.unsqueeze(dim=-1).shape}")  # [2,3,1] - 마지막 위치에 차원 추가  
    print(f"unsqueeze(dim=-2): {tensor.unsqueeze(dim=-2).shape}")  # [2,1,3] - 마지막에서 두 번째 위치에 차원 추가  
    print(f"unsqueeze(dim=-3): {tensor.unsqueeze(dim=-3).shape}")  # [1,2,3] - 마지막에서 세 번째(첫 번째) 위치에 차원 추가  
    
    # 3. 여러 번 unsqueeze 연속 적용  
    print(f"\n여러 차원 순차적으로 unsqueeze:")  
    result = tensor.unsqueeze(dim=0).unsqueeze(dim=-1)  
    print(f"unsqueeze(0) 후 unsqueeze(-1) 결과: {result.shape}")  # [1,2,3,1]  
    
    # 4. 1차원 텐서에 unsqueeze 적용  
    vector = torch.tensor([1, 2, 3, 4])  # 형태: [4]  
    print(f"\n1차원 벡터 형태: {vector.shape}")  
    print(f"행 벡터로 변환 - unsqueeze(0): {vector.unsqueeze(0).shape}")  # [1,4] (행 벡터)  
    print(f"열 벡터로 변환 - unsqueeze(1): {vector.unsqueeze(1).shape}")  # [4,1] (열 벡터)  
    
    # 5. 인플레이스 연산 - 원본 변경  
    tensor_copy = tensor.clone()  
    print(f"\n인플레이스 연산 전 형태: {tensor_copy.shape}")  
    tensor_copy.unsqueeze_(dim=0)  # 인플레이스 연산 (원본 변경)  
    print(f"unsqueeze_(0) 후 원본 형태: {tensor_copy.shape}")  
    
    # 6. 실제 사용 사례: 배치 차원 추가  
    sample = torch.randn(3, 224, 224)  # 단일 이미지 [채널, 높이, 너비]  
    print(f"\n단일 이미지 형태: {sample.shape}")  
    batch = sample.unsqueeze(0)  # 배치 차원 추가 [배치, 채널, 높이, 너비]  
    print(f"배치 차원 추가 후: {batch.shape}")  
    
    # 7. dim 파라미터의 다양한 문법  
    print(f"\n다양한 dim 파라미터 문법:")  
    print(f"unsqueeze(0): {tensor.unsqueeze(0).shape}")          # 위치 인자  
    print(f"unsqueeze(dim=0): {tensor.unsqueeze(dim=0).shape}")  # 키워드 인자  

# 함수 실행  
demonstrate_unsqueeze_with_dim()

원본 텐서 형태: torch.Size([2, 3])

다양한 위치에 차원 추가:
unsqueeze(dim=0): torch.Size([1, 2, 3])
unsqueeze(dim=1): torch.Size([2, 1, 3])
unsqueeze(dim=2): torch.Size([2, 3, 1])

음수 인덱스 사용:
unsqueeze(dim=-1): torch.Size([2, 3, 1])
unsqueeze(dim=-2): torch.Size([2, 1, 3])
unsqueeze(dim=-3): torch.Size([1, 2, 3])

여러 차원 순차적으로 unsqueeze:
unsqueeze(0) 후 unsqueeze(-1) 결과: torch.Size([1, 2, 3, 1])

1차원 벡터 형태: torch.Size([4])
행 벡터로 변환 - unsqueeze(0): torch.Size([1, 4])
열 벡터로 변환 - unsqueeze(1): torch.Size([4, 1])

인플레이스 연산 전 형태: torch.Size([2, 3])
unsqueeze_(0) 후 원본 형태: torch.Size([1, 2, 3])

단일 이미지 형태: torch.Size([3, 224, 224])
배치 차원 추가 후: torch.Size([1, 3, 224, 224])

다양한 dim 파라미터 문법:
unsqueeze(0): torch.Size([1, 2, 3])
unsqueeze(dim=0): torch.Size([1, 2, 3])


### Type Casting
- 이름.자료형() 형태로 텐서 형변환함
- 어떤 자료형 있는지 잘 알아둘것

In [14]:
import torch  

def demonstrate_type_casting():  
    """PyTorch 텐서 타입 캐스팅 종합 예제"""  
    
    print("=" * 50)  
    print("기본 텐서 생성")  
    print("=" * 50)  
    x = torch.tensor([1.5, 2.0, 3.7])  
    print(f"기본 텐서:      {x}")  
    print(f"데이터 타입:    {x.dtype}")  # 기본은 float32  
    
    print("\n" + "=" * 50)  
    print("to() 메서드를 사용한 타입 변환")  
    print("=" * 50)  
    x_float64 = x.to(torch.float64)  # 또는 x.to(dtype=torch.float64)  
    x_int32 = x.to(torch.int32)  
    x_bool = x.to(torch.bool)  
    
    print(f"float64로 변환: {x_float64}")  
    print(f"타입:           {x_float64.dtype}")  
    print("")  
    print(f"int32로 변환:   {x_int32}")  
    print(f"타입:           {x_int32.dtype}")  
    print("")  
    print(f"bool로 변환:    {x_bool}")  
    print(f"타입:           {x_bool.dtype}")  
    
    print("\n" + "=" * 50)  
    print("타입별 특화 메서드 사용")  
    print("=" * 50)  
    x_float = x.float()    # float32로 변환  
    x_double = x.double()  # float64로 변환  
    x_half = x.half()      # float16으로 변환  
    x_long = x.long()      # int64로 변환  
    x_int = x.int()        # int32로 변환  
    
    print(f"float():        {x_float}")  
    print(f"타입:           {x_float.dtype}")  
    print("")  
    print(f"double():       {x_double}")  
    print(f"타입:           {x_double.dtype}")  
    print("")  
    print(f"half():         {x_half}")  
    print(f"타입:           {x_half.dtype}")  
    print("")  
    print(f"long():         {x_long}")  
    print(f"타입:           {x_long.dtype}")  
    print("")  
    print(f"int():          {x_int}")  
    print(f"타입:           {x_int.dtype}")  
    
    print("\n" + "=" * 50)  
    print("텐서 생성 시 타입 지정")  
    print("=" * 50)  
    y_float32 = torch.tensor([1, 2, 3], dtype=torch.float32)  
    y_int64 = torch.tensor([1, 2, 3], dtype=torch.int64)  
    y_bool = torch.tensor([1, 0, 1], dtype=torch.bool)  
    
    print(f"float32로 생성: {y_float32}")  
    print(f"타입:           {y_float32.dtype}")  
    print("")  
    print(f"int64로 생성:   {y_int64}")  
    print(f"타입:           {y_int64.dtype}")  
    print("")  
    print(f"bool로 생성:    {y_bool}")  
    print(f"타입:           {y_bool.dtype}")  
    
    print("\n" + "=" * 50)  
    print("타입 변환 시 데이터 변화 확인")  
    print("=" * 50)  
    z = torch.tensor([1.7, 2.3, 3.9])  
    print(f"원본:                 {z}")  
    print(f"원본 타입:            {z.dtype}")  
    print("")  
    print(f"int()로 변환:         {z.int()}")         # 소수점 버림(절삭)  
    print(f"변환 후 타입:         {z.int().dtype}")  
    print("")  
    print(f"bool()로 변환:        {z.bool()}")        # 0 외 값은 모두 True  
    print(f"변환 후 타입:         {z.bool().dtype}")  
    print("")  
    print(f"float16으로 변환:     {z.half()}")        # 정밀도 감소 가능성  
    print(f"변환 후 타입:         {z.half().dtype}")  
    
    print("\n" + "=" * 50)  
    print("연산에서의 타입 변환")  
    print("=" * 50)  
    a = torch.tensor([1, 2, 3], dtype=torch.int)  
    b = torch.tensor([0.1, 0.2, 0.3], dtype=torch.float)  
    result = a + b  
    
    print(f"a:               {a}")  
    print(f"a 타입:          {a.dtype}")  
    print("")  
    print(f"b:               {b}")  
    print(f"b 타입:          {b.dtype}")  
    print("")  
    print(f"a + b:           {result}")  # 결과는 float (승격)  
    print(f"결과 타입:       {result.dtype}")  
    
    print("\n" + "=" * 50)  
    print("메모리 효율성")  
    print("=" * 50)  
    full_tensor = torch.ones(5, 5, dtype=torch.float32)  
    half_tensor = full_tensor.half()  
    byte_tensor = torch.ones(5, 5, dtype=torch.uint8)  
    
    float32_memory = full_tensor.element_size() * full_tensor.numel()  
    float16_memory = half_tensor.element_size() * half_tensor.numel()  
    uint8_memory = byte_tensor.element_size() * byte_tensor.numel()  
    
    print(f"float32 데이터 타입:  {full_tensor.dtype}")  
    print(f"float32 메모리:       {float32_memory} 바이트")  
    print("")  
    print(f"float16 데이터 타입:  {half_tensor.dtype}")  
    print(f"float16 메모리:       {float16_memory} 바이트")  
    print("")  
    print(f"uint8 데이터 타입:    {byte_tensor.dtype}")  
    print(f"uint8 메모리:         {uint8_memory} 바이트")  
    
    print("\n" + "=" * 50)  
    print("불리언 마스킹")  
    print("=" * 50)  
    mask = torch.tensor([True, False, True, False, True])  
    values = torch.arange(5, dtype=torch.float)  
    
    print(f"마스크:              {mask}")  
    print(f"마스크 타입:         {mask.dtype}")  
    print("")  
    print(f"값:                  {values}")  
    print(f"값 타입:             {values.dtype}")  
    print("")  
    print(f"마스킹 결과:         {values[mask]}")  
    print("")  
    print(f"마스크를 float로:    {mask.float()}")  # True=1.0, False=0.0  
    print(f"변환 후 타입:        {mask.float().dtype}")  
    print("")  
    print(f"마스크로 계산:       {values * mask.float()}")  
    print(f"계산 결과 타입:      {(values * mask.float()).dtype}")  

# 함수 실행  
demonstrate_type_casting()

기본 텐서 생성
기본 텐서:      tensor([1.5000, 2.0000, 3.7000])
데이터 타입:    torch.float32

to() 메서드를 사용한 타입 변환
float64로 변환: tensor([1.5000, 2.0000, 3.7000], dtype=torch.float64)
타입:           torch.float64

int32로 변환:   tensor([1, 2, 3], dtype=torch.int32)
타입:           torch.int32

bool로 변환:    tensor([True, True, True])
타입:           torch.bool

타입별 특화 메서드 사용
float():        tensor([1.5000, 2.0000, 3.7000])
타입:           torch.float32

double():       tensor([1.5000, 2.0000, 3.7000], dtype=torch.float64)
타입:           torch.float64

half():         tensor([1.5000, 2.0000, 3.6992], dtype=torch.float16)
타입:           torch.float16

long():         tensor([1, 2, 3])
타입:           torch.int64

int():          tensor([1, 2, 3], dtype=torch.int32)
타입:           torch.int32

텐서 생성 시 타입 지정
float32로 생성: tensor([1., 2., 3.])
타입:           torch.float32

int64로 생성:   tensor([1, 2, 3])
타입:           torch.int64

bool로 생성:    tensor([ True, False,  True])
타입:           torch.bool

타입 변환 시 데이터 변화 확인
원본:     

### Concatenate
- torch.cat([x.y],dim=0)
- 두 행렬을 지정된 차원에 이어붙인다
    - 출력행렬의 크기는 지정된 차원만 커진다
    - [2,3], [2,3] 크기의 행렬을 dim=1 로 이어붙이면
    - [2,6] 크기의 행렬이 됨

In [15]:
import torch  

# 2차원 텐서 생성  
x = torch.FloatTensor([[1, 2], [3, 4]])  
y = torch.FloatTensor([[5, 6], [7, 8]])  

# dim=0으로 연결 (행 방향)  
result_dim0 = torch.cat([x, y], dim=0)  
print(result_dim0)  
# 출력:  
# tensor([[1., 2.],  
#         [3., 4.],  
#         [5., 6.],  
#         [7., 8.]])  

# dim=1로 연결 (열 방향)  
result_dim1 = torch.cat([x, y], dim=1)  
print(result_dim1)  
# 출력:  
# tensor([[1., 2., 5., 6.],  
#         [3., 4., 7., 8.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### stack
- 지정된 모든 행렬을 dim 차원에 쌓아 새로운 차원을 만들고, 
- 차원이 하나 커진 행렬을 출력한다.
- 이떄 지정된 dim 차원의 크기는 입력 행렬의 갯수임
- 모든 입력 행렬들은 같은 크기를 가져야 한다


In [16]:
import torch  

# 크기가 [4]인 1차원 텐서 생성  
a = torch.tensor([1, 2, 3, 4])      # shape: [4]  
b = torch.tensor([5, 6, 7, 8])      # shape: [4]  
c = torch.tensor([9, 10, 11, 12])   # shape: [4]  

# dim=0으로 stack (첫 번째 차원에 쌓기)  
stacked = torch.stack([a, b, c], dim=0)  
print("dim=0 결과:")  
print(stacked)  
print("shape:", stacked.shape)      # torch.Size([3, 4])  
#                                     ↑   ↑  
#                                     |   요소 개수 4개  
#                                     텐서 3개 입력  

# dim=1로 stack (두 번째 차원에 쌓기)  
stacked_dim1 = torch.stack([a, b, c], dim=1)  
print("\ndim=1 결과:")  
print(stacked_dim1)  
print("shape:", stacked_dim1.shape)  # torch.Size([4, 3])  
#                                      ↑   ↑  
#                                      |   텐서 3개 입력  
#                                      요소 개수 4개

dim=0 결과:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])

dim=1 결과:
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])
shape: torch.Size([4, 3])


### Ones and Zeros
- 모든 요소가 0,1인 텐서 생성함
- _like
    - 입력 텐서와 동일한 크기의 모든 요소가 0,1 인 텐서 생성함
- full
    - 특정 값으로 채워진 텐서 생성

In [18]:
import torch  

print("===== 기본 초기화 함수 =====")  
# torch.zeros()로 0으로 채운 텐서 생성  
zeros_tensor = torch.zeros(2, 3)  
print("torch.zeros(2, 3):")  
print(zeros_tensor)  
print("데이터 타입:", zeros_tensor.dtype)  

# torch.ones()로 1로 채운 텐서 생성  
ones_tensor = torch.ones(2, 4)  
print("\ntorch.ones(2, 4):")  
print(ones_tensor)  

# 특정 데이터 타입 지정  
int_zeros = torch.zeros(2, 2, dtype=torch.int32)  
print("\n정수형 zeros:")  
print(int_zeros)  
print("데이터 타입:", int_zeros.dtype)  

print("\n===== _like 함수들 =====")  
# 기준이 될 텐서 생성  
base_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])  
print("기준 텐서:")  
print(base_tensor)  
print("크기:", base_tensor.shape)  

# zeros_like  
zeros_like_tensor = torch.zeros_like(base_tensor)  
print("\ntorch.zeros_like(base_tensor):")  
print(zeros_like_tensor)  

# ones_like  
ones_like_tensor = torch.ones_like(base_tensor)  
print("\ntorch.ones_like(base_tensor):")  
print(ones_like_tensor)  

# 데이터 타입 변경  
float_ones_like = torch.ones_like(base_tensor, dtype=torch.float)  
print("\n실수형 ones_like:")  
print(float_ones_like)  
print("데이터 타입:", float_ones_like.dtype)  

print("\n===== 특정 값으로 채우기 =====")  
# 특정 값으로 채우기 - 방법 1  
fives = torch.ones(2, 3) * 5  
print("torch.ones(2, 3) * 5:")  
print(fives)  

# 특정 값으로 채우기 - 방법 2 (torch.full)  
full_tensor = torch.full((2, 3), 7.5)  
print("\ntorch.full((2, 3), 7.5):")  
print(full_tensor)  

# full_like  
full_like_tensor = torch.full_like(base_tensor, 9)  
print("\ntorch.full_like(base_tensor, 9):")  
print(full_like_tensor)  

===== 기본 초기화 함수 =====
torch.zeros(2, 3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
데이터 타입: torch.float32

torch.ones(2, 4):
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

정수형 zeros:
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
데이터 타입: torch.int32

===== _like 함수들 =====
기준 텐서:
tensor([[1, 2, 3],
        [4, 5, 6]])
크기: torch.Size([2, 3])

torch.zeros_like(base_tensor):
tensor([[0, 0, 0],
        [0, 0, 0]])

torch.ones_like(base_tensor):
tensor([[1, 1, 1],
        [1, 1, 1]])

실수형 ones_like:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
데이터 타입: torch.float32

===== 특정 값으로 채우기 =====
torch.ones(2, 3) * 5:
tensor([[5., 5., 5.],
        [5., 5., 5.]])

torch.full((2, 3), 7.5):
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])

torch.full_like(base_tensor, 9):
tensor([[9, 9, 9],
        [9, 9, 9]])


### In-place Operation
- 함수 맨 뒤에 _추가해 사용
- 새 텐서를 반환하지 않고 기존 텐서의 메모리를 직접 수정


In [ ]:
import torch  

# 기본 텐서 생성  
x = torch.ones(3, 3)  
print("원본 x:")  
print(x)  

# 1. add_: 덧셈 in-place 연산  
x.add_(5)  # x = x + 5와 동일한 결과지만 새 메모리 할당 없음  
print("\nadd_(5) 후:")  
print(x)  

# 2. mul_: 곱셈 in-place 연산  
x.mul_(2)  # x = x * 2  
print("\nmul_(2) 후:")  
print(x)  

# 3. zero_: 모든 원소를 0으로 초기화  
x.zero_()  # x = torch.zeros_like(x)  
print("\nzero_() 후:")  
print(x)  

# 4. fill_: 특정 값으로 채우기  
x.fill_(7)  # x의 모든 원소를 7로 변경  
print("\nfill_(7) 후:")  
print(x)  

# 5. copy_: 다른 텐서의 값 복사  
y = torch.randn(3, 3)  
x.copy_(y)  # y의 값을 x에 복사  
print("\ncopy_(y) 후:")  
print(x)  
print("원본 y:")  
print(y)

원본 x:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

add_(5) 후:
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

mul_(2) 후:
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

zero_() 후:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

fill_(7) 후:
tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

copy_(y) 후:
tensor([[ 0.8483,  0.7929, -1.0229],
        [ 1.9905, -1.8861, -0.1985],
        [-0.4668, -0.5371, -0.1189]])
원본 y:
tensor([[ 0.8483,  0.7929, -1.0229],
        [ 1.9905, -1.8861, -0.1985],
        [-0.4668, -0.5371, -0.1189]])
